/**
 ******************************************************************************
 * @file    mx.c
 * @author  SRA - GPM
 * 
 * 
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the eLooM framework.
 *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
 */

#include "mx.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"
#include "i2c.h"
#include "dma.h"


/**
 * (USER_BUTTON_1) Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_UB1InitParams = {
    MX_GPIO_PC13_Init,
    EXTI15_10_IRQn,
    B1_Pin,
    B1_GPIO_Port
};

/**
 * LD2 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_LD2InitParams = {
    MX_GPIO_PA5_Init,
    UsageFault_IRQn, /* not used. */
    LD2_Pin,
    LD2_GPIO_Port
};

/**
 * TIM7 initialization parameters.
 */
const MX_TIMParams_t MX_TIM7InitParams = {
    .p_mx_init_f = MX_TIM7_Init,
    .p_tim = &htim7,
    .irq_n = TIM7_IRQn
};

/**
 * TIM16 initialization parameters.
 */
const MX_TIMParams_t MX_TIM16InitParams = {
    .p_mx_init_f = MX_TIM16_Init,
    .p_tim = &htim16,
    .irq_n = TIM1_UP_TIM16_IRQn
};

/**
 * I2C1 initialization parameters.
 */
const MX_I2CParams_t MX_I2C1InitParams = {
    .p_mx_init_f = MX_I2C1_Init,
    .p_i2c_handle = &hi2c1,
    .p_mx_dma_init_f = MX_DMA_InitCustom,
    .i2c_er_irq_n = I2C2_ER_IRQn,
    .i2c_ev_irq_n = I2C2_EV_IRQn,
    .i2c_dma_rx_irq_n = DMA1_Channel1_IRQn,
    .i2c_dma_tx_irq_n = DMA1_Channel2_IRQn
};

/**
  * (INT1_DHCX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_DHCXInitParams =
{
  MX_GPIO_PB10_Init,
  INT1_DHCX_EXTI_IRQn, /*!< NOT USED */
  INT1_DHCX_Pin,
  INT1_DHCX_GPIO_Port
};
