/**
 ******************************************************************************
 * @file    mx.c
 * @author  SRA - GPM
 * 
 * @date    Apr 9, 2021
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an ODeV driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the ODeV framework.
 *
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *                             
 *
 ******************************************************************************
 */

#include "mx.h"
#include "adc.h"
#include "crc.h"
#include "spi.h"
#include "dma.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"


/**
 * ADC1 initialization parameters.
 */
const MX_ADC1Params_t MX_ADC1InitParams = {
    .p_adc = &hadc1,
    .p_mx_init_f = MX_ADC1_Init
};

/**
 * SPI1 initialization parameters.
 */
const MX_SPIParams_t MX_SPI1InitParams = {
    .p_mx_init_f = MX_SPI1_Init,
    .p_spi_handle  = &hspi1,
    .p_mx_dma_init_f = MX_DMA_InitCustom,
    .spi_dma_rx_irq_n = DMA1_Channel1_IRQn,
    .spi_dma_tx_irq_n = DMA1_Channel2_IRQn
};

/**
 * CRC initialization parameters.
 */
const MX_CRCParams_t MX_CRCInitParams = {
    .p_crc = &hcrc,
    .p_mx_init_f = MX_CRC_Init
};

/**
 * PE4 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PE4InitParams = {
    ISM330DHCX_INT1_INIT,
    ISM330DHCX_INT1_EXTI_IRQn,
    ISM330DHCX_INT1_Pin,
    ISM330DHCX_INT1_GPIO_Port
};


/**
 * PA4 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PA4InitParams = {
    SPI_ISM330DHCX_CS_INIT,
    UsageFault_IRQn, /*!< NOT USED */
    SPI_ISM330DHCX_CS_Pin,
    SPI_ISM330DHCX_CS_GPIO_Port
};


/**
 * PE3 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PE3InitParams = {
    IIS3DWB_INT1_INIT,
    IIS3DWB_INT1_EXTI_IRQn,
    IIS3DWB_INT1_Pin,
    IIS3DWB_INT1_GPIO_Port
};


/**
 * PA15 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PA15InitParams = {
    SPI_IIS3DWB_CS_INIT,
    UsageFault_IRQn, /*!< NOT USED */
    SPI_IIS3DWB_CS_Pin,
    SPI_IIS3DWB_CS_GPIO_Port
};

/**
 * TIM2 initialization parameters.
 */
const MX_TIMParams_t MX_TIM2InitParams = {
    .p_mx_init_f = MX_TIM2_Init,
    .p_tim = &htim2,
    .irq_n = TIM2_IRQn
};

/**
 * PE1 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PE1InitParams = {
    MX_GPIO_PE1_Init,
    UsageFault_IRQn, /*!< NOT USED */
    GPIO_PIN_1,
    GPIOE
};

/**
 * PE0 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PE0InitParams = {
    MX_GPIO_PE0_Init,
    UsageFault_IRQn, /*!< NOT USED */
    GPIO_PIN_0,
    GPIOE
};

/**
 * PD12 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PD12InitParams = {
    MX_GPIO_PD12_Init,
    UsageFault_IRQn, /*!< NOT USED */
    GPIO_PIN_12,
    GPIOD
};

/**
 * PB13 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PB13InitParams = {
    MX_GPIO_PB13_Init,
    BUTTON_USER_EXTI_IRQn,
    GPIO_PIN_13,
    GPIOB
};

/**
 * PD2 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PD2InitParams = {
    MX_GPIO_PD2_Init,
    HardFault_IRQn, /* Not used */
    GPIO_PIN_2,
    GPIOD
};
